from typing import Callable, Literal, Sequence
import numpy as np
from numpy.typing import NDArray

class IMUReading:
    accel: Sequence[float]
    gyro: Sequence[float]
    quaternion: Sequence[float]
    timestamp_ns: int

class DeviceInfo:
    device_type: str
    firmware_version: str
    product_id: int

class IMU:
    def read(self) -> IMUReading: ...
    def start_stream(self, callback: Callable[[IMUReading], None], interval_ms: int = 16) -> None: ...
    def stop_stream(self) -> None: ...

class Camera:
    def capture(self) -> NDArray[np.uint8]: ...

class DepthCamera:
    def capture(self, side: Literal["left", "right"] = "left") -> NDArray[np.uint16]: ...

class Mic:
    def record(self, duration_ms: int, sample_rate: int = 48000) -> NDArray[np.float32]: ...

class USBCamera:
    device_index: int | None
    active_index: int | None

    def __init__(
        self,
        device_index: int | None = None,
        max_probe: int = 8,
        width: int | None = None,
        height: int | None = None,
    ) -> None: ...
    def open(self) -> int: ...
    def close(self) -> None: ...
    def capture(self) -> NDArray[np.uint8]: ...
    def describe_active_device(self) -> str: ...
    @classmethod
    def available_indices(cls, max_probe: int = 8) -> list[int]: ...
    @classmethod
    def describe_index(cls, index: int) -> str: ...

class AudioRecorder:
    def __init__(
        self,
        input_device_index: int | None = None,
        output_device_index: int | None = None,
        frames_per_buffer: int = 1024,
    ) -> None: ...
    def close(self) -> None: ...
    def record(
        self,
        duration_ms: int,
        sample_rate: int = 48000,
        channels: int = 1,
    ) -> NDArray[np.float32]: ...
    def play(
        self,
        samples: NDArray[np.float32],
        sample_rate: int = 48000,
        channels: int = 1,
    ) -> None: ...
    @staticmethod
    def list_input_devices() -> list[dict[str, object]]: ...

class Device:
    imu: IMU
    camera: Camera
    depth: DepthCamera
    mic: Mic

    def __init__(self, product_id: int | None = None) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def is_connected(self) -> bool: ...
    def info(self) -> DeviceInfo: ...
    def set_brightness(self, value: int) -> None: ...
    def get_brightness(self) -> int: ...
    def set_display_mode(self, mode: int) -> None: ...
    def set_volume(self, value: int) -> None: ...
