"""Centralized configuration constants for the Cleo platform."""

SENSOR_PORT = 50051
TRANSCRIPTION_PORT = 50052
DATA_PORT = 50053
ASSISTANT_PORT = 50054
COLOR_BLIND_PORT = 50060
OBJECT_RECOGNITION_PORT = 50061
NAVIGATION_ASSIST_PORT = 50062

SENSOR_ADDRESS = f"localhost:{SENSOR_PORT}"
TRANSCRIPTION_ADDRESS = f"localhost:{TRANSCRIPTION_PORT}"
DATA_ADDRESS = f"localhost:{DATA_PORT}"
ASSISTANT_ADDRESS = f"localhost:{ASSISTANT_PORT}"
COLOR_BLIND_ADDRESS = f"localhost:{COLOR_BLIND_PORT}"
OBJECT_RECOGNITION_ADDRESS = f"localhost:{OBJECT_RECOGNITION_PORT}"
NAVIGATION_ASSIST_ADDRESS = f"localhost:{NAVIGATION_ASSIST_PORT}"

SENSOR_DEFAULT_FPS = 30.0
SENSOR_DEFAULT_CHUNK_MS = 160
SENSOR_DEFAULT_SAMPLE_RATE = 48000
SENSOR_AUDIO_BUFFER_SECONDS = 30

TRANSCRIPTION_ACCUMULATION_SECONDS = 1.5
TRANSCRIPTION_SILENCE_THRESHOLD_RMS = 0.01
TRANSCRIPTION_FINAL_SILENCE_MS = 800
TRANSCRIPTION_PREROLL_CHUNKS = 2

EMBEDDING_DIMENSION = 1024
BEDROCK_MODEL_ID = "amazon.nova-2-multimodal-embeddings-v1:0"
BEDROCK_REGION = "us-east-1"

VIDEO_CLIP_FPS = 30.0
VIDEO_EMBED_FPS = 5.0
VIDEO_CLIP_DURATION_SECONDS = 15.0

VIDEO_STORAGE_DIR = "data/videos"
